duke-git/lancet

- slice/slice.go
Waste of memory for those unused indexes. It got replaced by a simple
boolean to keep track of it.
> Some: allocate slice to keep track of unused indexes is not necessary

- strutil/string.go
* Use unicode.ToUpper func to convert first letter in string to upper case
letter.
* Preallocate memory with correct length and cap because the final
string length is not changing.
> Optimized: Capitalize

- slice/slice.go
Use counter to verify all elements passed the perdicate func.
Replace slice of indexes with int counter.
> Every: use int counter

- slice/slice.go
- slice/slice_test.go
IntSlice and StringSlice: preallocate memory up front for output slice.
Instead returning a error throw a panic because most likely it's a
programming error.
Contain: rename slice to iterableType and add default case for type
mismatches
> Slice: Optimize slice func tools

- README.md
- README_zh-CN.md
- slice/slice.go
- slice/slice_test.go
Group by: split slice into two groups, applies on each slice element a
predicate func to categorize this element.
Changes
* Add groub by func
* Add test case for this func
> Slice: Add GroupBy func

- README.md
- README_zh-CN.md
- slice/slice.go
- slice/slice_test.go
The current behavior can result into wired edge cases.
**Current behavior**
if find was unsuccessfully then it will return the first element of the
slice
**Desired behavior**
if find was unsuccessfully then it should return negative ok and a none
value
> Slice: find nothing case

- slice/slice.go
Use less memory and cpu resources to filter out elements from the slice.
> Filter: remove second loop and indexes slice

- strutil/string.go
- strutil/string_test.go
strings.Split return with empty string. strutil.SplitEx can remove empty string by set 'removeEmptyString = true'
> feat: strutil.SplitEx. Split a given string whether the result contains empty string

- netutil/http_test.go
Signed-off-by: Abirdcfly <fp544037857@gmail.com>
see https://go.dev/play/p/jlrIP76KOCf for example:
```go
package main
import (
"log"
"testing"
)
func TestLastIndex(t *testing.T) {
log.Fatalf("this line will print and exit")
t.Errorf("this line can't print")
}
/* output:
=== RUN   TestLastIndex
2009/11/10 23:00:00 this line will print and exit
Program exited.
*/
```
> delete minor unreachable code caused by log.Fatal

- datastructure/set/set.go
Using `bool` as a value takes up one more byte of space, and an empty structure does not occupy any memory space.
> feat: Set struct uses empty struct as value

- lancetconstraints/constraints.go
- mathutil/mathutil_test.go
Support type alias for Number constraint. eg:
```go
func TestMax() {
type Integer int
assert.Equal(Max(Integer(1), Integer(0)), Integer(1))
}
```
> feat: support type alias for Number constraint

- slice/slice.go
- slice/slice_test.go
The indexof function is a commonly used function, but it is not practical to query the index by polling the array each time.
I introduced a hash table setting that is consistent with the program life cycle to be compatible with large array query indexes and the same array multiple query indexes.
At the same time, I set the highest storage number to prevent memory overflow.
Now, we can safely use it to query the index of any value in the array without worrying about them endlessly polling
> feat: A more reasonable IndexOf function

- convertor/convertor.go
- convertor/convertor_test.go
当前使用`StructToMap`时，如果json tag使用属性或者`-`会报错，修复此问题
> add support json tag attribute for StructToMap function

- convertor/convertor.go
- convertor/convertor_test.go
- netutil/http.go
- netutil/http_test.go
- netutil/net_example_test.go
- retry/retry_example_test.go
- structutil/field.go
- structutil/struct.go
- structutil/struct_test.go
- structutil/tag.go
目前对于struct的转换方法写的比较简陋，考虑到struct的方法可能会很多，所以抽象出来单独封装，便于维护，整体逻辑大致如下：
- 封装`Struct`对象作为抽象，作为对外统一暴露方法的结构体
- 封装`Field`为`Struct`的属性，提供若干方便的方法
- 封装`Tag`为`Field`的标签，提供若干边界方法
`Struct`目前提供方法有：
```go
// 将struct转换为map
// 做了一部分优化，同时修复了 #77
ToMap(v any) (map[string]any, error)
// 提供获取struct的属性列表方法，此属性为为封装`Field`
Fields() []*Fields
```
`Field`目前提供方法：
```go
// 获取Field抽象Tag对象
Tag() *Tag
// 获取Field值
Value() any
// 判断是否为嵌入属性
IsEmbedded() bool
// 判断属性是否公开
IsExported() bool
// 判断属性是否零值
IsZero() bool
// 获取属性名
Name() string
// 获取Kind
Kind() reflect.Kind
```
`Tag`目前提供方法：
```go
// 判断tag选项
HasOption(opt string) bool
// 判断是否为空tag
IsEmpty() bool
```
将convertor中的StructToMap逻辑迁移至`structutil`中的`ToMap`，为兼容老版本提供方法暂留。
修复#77
> Add StructUtil for provide more rich functions 

- slice/slice.go
- slice/slice_example_test.go
- slice/slice_test.go
- add FindBy that a result will be without unrefrence for slice package
- add `Deprecated` tag for `Find`, `FindLast`
> feat: add FindBy function that the result will be no longer requiring derefrencing

- README.md
- docs/pointer.md
- pointer/pointer.go
- pointer/pointer_examples_test.go
- pointer/pointer_test.go
When I try to use `Unwarp` in the `pointer` package, it panics when I pass it a nil pointer.
This is not what I want; I want it to return a zero value of the pointer's type.
Or the fallback value I provide.
So I created two new functions, `UnwarpOr` and `UnwarpOrDefault`, to do this.
1. If the pointer is nil, `UnwarpOr` will return the fallback value.
2. If the pointer is nil, `UnwarpOrDefault` will return the zero value of the type of the pointer.
> feat: add UnwarpOr and UnwarpOrDefault to pointer pkg

- compare/compare.go
- compare/compare_example_test.go
- compare/compare_test.go
- docs/compare.md
To determine the two floats are equal, we should check whether the difference is lesser than the precision value.
> feat: InDelta

- convertor/convertor_internal.go
- convertor/convertor_test.go
Skip invalid elements instead of valid elements when cloning a slice or an array.
> fix the bug in cloning slices

- fileutil/file.go
- fileutil/file_test.go
* Add support for seeking files and reading files one line at a time, sample usage is demonstrated in `fileutil/file_test.go`
* Add support for calculating folder's size recursively
This should implement #156
> feat: add support for seeking and read one line at a time from file

- datetime/datetime.go
- fileutil/file.go
1. WriteCsvFile自定义分割符;
2. 同时以分隔符为基础对单元格的值进行了转义处理;
3. map切片写入csv函数`WriteMapsToCSV`
4. 增加追踪函数执行时间的函数`TraceFuncTime`
> WriteCsvFile自定义分割符,增加map切片写入csv，增加追踪函数运行时间的函数

- datastructure/optional/optional.go
- datastructure/optional/optional_test.go
- internal/assert.go
Wrapper container with easy to understand helper methods.
Note: Documentation is missing
@duke-git Please review
> Add optional

- function/predicate.go
- function/predicate_test.go
Functional **nor** returns a composed predicate that represents the logical NOR of a list of predicates. It evaluates to true only if all predicates evaluate to false for the given value.
> Add functional nor predicate

- retry/retry.go
- retry/retry_example_test.go
- retry/retry_test.go
The aim of this policy is to enable the configuration of various types of backoff mathematical curves. Should this modification be deemed suitable, I will proceed to implement an exponential curve backoff policy and set of custom backoff policy 
**Warning: It's major break**
> Add retry backoff policy

- retry/retry.go
- retry/retry_example_test.go
- retry/retry_test.go
Adds exponential + jitter retry policy. To enable drastic slow down of sending out requests to any external system.
Jitter in computational contexts refers to the addition of a small random variation to a value to break the symmetric patterns
Will start soon to add doc sections ;)
> Add exponential With jitter backoff

- retry/retry.go
- retry/retry_example_test.go
- retry/retry_test.go
Users should have the capability to customize the backoff pattern and accordingly adjust it within the retry mechanism.
@duke-git Have a look please
> Add custom backoff setter

- datastructure/optional/optional.go
- datastructure/optional/optional_test.go
- docs/api/packages/datastructure/optional.md
- docs/en/api/packages/datastructure/optional.md
Utilize terminology from the Go SDK rather than introducing novel terms to describe concepts.
> Change naming

- datastructure/list/copyonwritelist.go
- datastructure/list/copyonwritelist_test.go
- docs/api/packages/datastructure/copyonwritelist.md
- docs/en/api/packages/datastructure/copyonwritelist.md
Allow users to apply functional predicates alongside 'index of' and 'last index of' search methods in this specialized list variant
Note: I am not fluent in Chinese; the Chinese document may require a revisions.
> CopyOnWriteList add IndexOfFunc and LastIndexOfFunc

- datastructure/hashmap/hashmap.go
- datastructure/hashmap/hashmap_test.go
The FilterByValue function is a method defined on the HashMap type. It generates a new HashMap containing only the elements that satisfy a specified condition, as determined by a predicate function applied to each element's value.
Note: Will add later doc
@duke-git Please review
> Hashmap: Add FilterByValue

- iterator/iterator.go
- iterator/iterator_test.go
- iterator/operation_test.go
**Major break**
Feature
Reset allows for the iteration process over a sequence to be restarted from the beginning. It enables reusing the iterator for multiple traversals without needing to recreate it.
Refactoring
It is a idiomatic practice to design functions and methods to return concrete struct types. This approach promotes flexibility and decoupling, allowing the calling code to work with any implementation that satisfies the interface
> Iterator: general refactoring and reset method

- docs/api/packages/mathutil.md
- docs/en/api/packages/mathutil.md
- mathutil/mathutil.go
- mathutil/mathutil_test.go
The range of supported types refers to [Round[T SignedNumber | UnsignedNumber](val T) T](https://github.com/tiny-craft/tiny-rdm/blob/main/backend/utils/math/math_util.go#L67)
Regarding the TruncRound method, it fails the original test when x is the literal 0, which is a refactoring that breaks compatibility. However, I believe few people would do this. 
Personally, I think it makes more intuitive sense for the parameter and return types to be consistent, while the semantics of the original function names are preserved for other functions.
> round related method support generics

- docs/api/packages/strutil.md
- docs/en/api/packages/strutil.md
- strutil/string.go
- strutil/string_example_test.go
- strutil/string_test.go
The Hamming distance is the number of positions at which the corresponding symbols are different
> Strutil: HammingDistance func

- docs/api/packages/function.md
- docs/en/api/packages/function.md
- function/function.go
- function/function_example_test.go
- function/function_test.go
AcceptIf returns another function of the same signature as the apply function but also includes a bool value to indicate success or failure. 
A predicate function that takes an argument of type T and returns a bool. 
An apply function that also takes an argument of type T and returns a modified value of the same type.
> Function: AcceptIf

- docs/api/packages/mathutil.md
- docs/en/api/packages/mathutil.md
- mathutil/mathutil.go
- mathutil/mathutil_exmaple_test.go
- mathutil/mathutil_test.go
__mathutil__ : add `Div` ,`FloorToFloat`, `FloorToString`, `CeilToFloat`, `CeilToString`
> create rc branch for release candidate

- docs/api/packages/slice.md
- docs/en/api/packages/slice.md
- slice/slice.go
- slice/slice_example_test.go
- slice/slice_test.go
Splits a slice into two based on a predicate function. It starts appending to the second slice after the first element that matches the predicate. All elements after the first match are included in the second slice, regardless of whether they match the predicate or not.
> Slice: break

- docs/api/packages/slice.md
- docs/en/api/packages/slice.md
- slice/slice.go
- slice/slice_example_test.go
- slice/slice_test.go
* LeftPadding adds padding to the left begin of a slice.
* RightPadding adds padding to the right end of a slice.
> Slice: padding

- datastructure/set/set.go
- datastructure/set/set_test.go
The Pop method of the collection does not guarantee order,  and there is no need to convert it to a slice
it can be directly deleted.
> refactor(set): pop method randomly removes an element and return

- netutil/http.go
- netutil/http_test.go
Add the Proxy parameter in HttpClientConfig struct to conveniently use the proxy IP to send requests.
> fix(netutil): Add proxy IP to send request

- slice/slice.go
- slice/slice_test.go
The Concat method and the Merge method serve essentially the same purpose, and in the slices package of Go 1.22, the same functionality is named Concat. Should one of them be deprecated?
> refactor(slice): optimize function

- slice/slice.go
优化slice.Unique()方法,使性能提高20倍以上.
对10万个随机切片进行去重:
原方法:
```
goos: linux
goarch: amd64
cpu: 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
BenchmarkUnique
BenchmarkUnique-8   	1000000000	         0.1229 ns/op
PASS
```
优化后的方法:
```
goos: linux
goarch: amd64
cpu: 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
BenchmarkUnique2
BenchmarkUnique2-8   	1000000000	         0.004338 ns/op
PASS
```
使用的随机切片如下:
```
func GetS (length int) []int {
rand.Seed(time.Now().UnixNano())
slice := make([]int, length)
for i := 0; i < length; i++ {
slice[i] = rand.Intn(10000)
}
return slice
}
```
> refactor slice.Unique()

- maputil/map.go
- maputil/map_test.go
fix: json tag omitempty convert error https://github.com/duke-git/lancet/issues/216
> fix(maputil): json tag omitempty convert error 

- convertor/convertor.go
- convertor/convertor_test.go
将structtomap的方式 如果传递指针进来做参数会导致panic ，修复可允许传递指针
> fix:convertor struct to map by struct ptr

- docs/api/packages/slice.md
- docs/en/api/packages/slice.md
- slice/slice.go
https://github.com/golang/go/blob/master/src/slices/slices.go#L476 
Deprecate functions with the same functionality.
> perf(slice): Concat() make a clearer panic description, like standard library

- pointer/pointer.go
- pointer/pointer_examples_test.go
1. UnwarpOr
2. UnwarpOrDefault
3. ExtractPointer
1. UnwrapOr
2. IsNil
> :bug: Fixing bug. about pointer package function, #227 #228

- strutil/string.go
In the strutil/string.go file, the function comment for ‘Pad’ is wrong. It should be Pad instead of PadStart.
> fix(strutil): rename PadStart to Pad.

- maputil/orderedmap.go
- maputil/orderedmap_test.go
set : when the key is present, the value of the data map should be set, not the value of the list
> fix(orderedmap): fix set bug

- slice/slice_concurrent.go
- slice/slice_internal.go
修复#255中描述的`type declarations inside generic functions are not currently supported`在go@1.18.x中的编译异常，实际上泛型函数内类型定义在1.20以后的版本才支持。
另外，可以考虑github action中将go版本调整为`1.18.10`避免未来再出现兼容性异常
> fix: fix compile error when go sdk version below go@1.20 (#255)

- algorithm/lrucache.go
- netutil/http.go
- netutil/http_test.go
feat(netutil): add async http request for http client mentioned in issue #253
> feat(netutil): add async http request for http client

- slice/slice.go
- slice/slice_concurrent.go
- slice/slice_test.go
Under this benchmark, sync.RWMutex performs better in terms of both performance and stability compared to sync.Map.
> perf(slice): make the IndexOf function thread-safe (#262)

- README.md
Hello team,
I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.
I wanted to update you that I've manually added the [Lancet Guru](https://gurubase.io/g/lancet) to Gurubase. Lancet Guru uses the data from this repo and data from the [docs](https://www.golancet.cn/en/) to answer questions by leveraging the LLM.
In this PR, I showcased the "Lancet Guru", which highlights that Lancet now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution.
Additionally, if you want me to …
> Introducing Lancet Guru on Gurubase.io

- fileutil/file.go
> fix(fileutil): unzip Chinese garbled code during decompression

- slice/slice_test.go
在slice/slice_test.go这个文件中，使用多个goroutine测试FilterConcurrent函数，在对返回的slice进行比较的时候，应该先进行排序，否则比较结果会出现概率性错误
> fix: fix slice_test.go ,We should not assume the order of the slice

- stream/stream.go
- stream/stream_example_test.go
- stream/stream_test.go
> feat: add ToMap for stream

- datastructure/queue/arrayqueue.go
As explained in https://github.com/duke-git/lancet/issues/312, the current implementation of `ArrayQueue.Back()` is incorrect. 
This small PR fixes this bug.
> fix: ArrayQueue.Back() implementation

- slice/slice.go
- slice/slice_internal.go
- slice/slice_test.go
The `RightPadding` and `LeftPadding` functions in the `slice` package have some issues.  Also discussed in issue(#320 ):
1.  `RightPadding` modifies the given slice in place, while  `LeftPadding` returns a copy of the slice with the padding (or the given slice if the paddingLenght is 0).  That is not consistent, and brings problems to the caller as it behaves different depending on the situation.
2. Both functions cannot deal with paddingLength negative values.
This can be shown by running the following code (or in Play https://go.dev/play/p/y7G86ZQjJBP):
```go
// You can edit this code!
// Click here and start typing.
package main
import (
"fmt"
"github.com/duke-git/lancet/v2/slice"
)
func main() {
nums := []int{1, 2, 3, 4, 5}
padded := slice.LeftPadding(nums, 0, 3)
fmt.Println(padded) …
```
> fix(package): [slice] Fix RigthPadding and LeftPadding
