duke-git/lancet

- validator/validator.go
Reduce executions time of pattern matching, regex patterns are expensive to
compile at runtime.
> Regex validators: Precompile all known regex patterns

- strutil/string.go
- strutil/string_test.go
Replace looping with slicing and utf8 func tools operations.
> LowerFirst: use slicing and utf8 func tools

- datetime/datetime.go
- datetime/datetime_test.go
Replace time parsing calls with less expensive operations
> datetime: optimized func calls

- function/function.go
- function/function_util.go
Place at first line of the function body a function type safe guard
check.
> function: catch earlier programming error

- README.md
- README_zh-CN.md
- slice/slice.go
- slice/slice_test.go
Returns true whether no elements of this slice match the provided predicate
func. Negated form of Every func
> Slice: Add none func

- README.md
- README_zh-CN.md
- slice/slice.go
- slice/slice_test.go
Returns the count of matched elements
> Slice: Add count func

- README.md
- README_zh-CN.md
- slice/slice.go
- slice/slice_test.go
* If slice len is zero then return false
* Convert find to generic form.
* If return T is nil then no items matched the predicate func
Note: I haven't found out jet how to construct a default value of none pointer T.
> Slice: find v2

- README.md
- README_zh-CN.md
- slice/slice.go
Use generic instead of reflection
> Slice: CountV2

- README.md
- README_zh-CN.md
- slice/slice.go
- slice/slice_test.go
Migrate from reflection to generic form
Note: after migration, old reverse must be removed
> Slice: reverse and shufffle v2

- README.md
- README_zh-CN.md
- function/watcher_test.go
- myconstraints/constraints.go
- slice/slice.go
Migrate from reflection to generic
> Slice: group by and without v2

- slice/slice.go
- slice/slice_test.go
Removed reverse func because it use to much cpu and add test cas for asc sort
> refactor: sort

- slice/slice.go
- slice/slice_test.go
ref: https://github.com/duke-git/lancet/commit/f1d7154179a4d94472bee9703097d78e6c37e9a7
> Slice: sort from v2 branch

- README.md
Fix the import example for convertor.
> docs(readme): fix convertor import example

- README.md
- README_zh-CN.md
- xerror/xerror.go
- xerror/xerror_test.go
Add a unwrap func helper
* Unwrap if err is nil then it returns a valid value otherwise it panics
> error: Add unwrap

- convertor/convertor.go
- convertor/convertor_test.go
- slice/slice.go
- slice/slice_test.go
ToPointer:返回任意类型指针.
ToSlicePointer: 返回可变参数的切片指针
ToSlice : 返回可变参数的切片
> Add ToPointer,ToSlicePointer,ToSlice  func

- fileutil/file_test.go
- netutil/net.go
- netutil/net_test.go
1: GetRequestPublicIp: return the requested public ip
2: IsInternalIP: verify an ip is intranet or not
>  feat: add func GetRequestPublicIp and IsInternalIP

- system/os.go
- system/os_test.go
System: Add the system bits judgment
> System: Add the system bits judgment

- datastructure/list/list.go
- datastructure/list/list_test.go
- docs/datastructure/list.md
- docs/maputil.md
Add LastIndexOf method to List and fix doc
LastIndexOf returns the index of the last occurrence of the value in this list.
if not found return -1
> list: add LastIndexOf

- datastructure/list/list.go
- datastructure/list/list_test.go
- docs/datastructure/list.md
* LastIndexOfFunc returns the index of the last occurrence of the value in this list satisfying f(data[i])
* IndexOfFunc returns the first index satisfying f(v)
> list: Add LastIndexOfFunc and IndexOfFunc method

- datastructure/list/list.go
- datastructure/list/list_test.go
- docs/datastructure/list.md
SubList returns a sub list of the original list between the specified fromIndex, inclusive, and toIndex, exclusive.
> list: add sublist method

- datastructure/list/list.go
- datastructure/list/list_test.go
- docs/datastructure/list.md
DeleteIf delete all satisfying f(data[i]), returns count of removed elements
> list: add DeleteIf method

- datastructure/list/list.go
- datastructure/list/list_test.go
- docs/datastructure/list.md
Cap return cap of the inner data
> List: add cap

- slice/slice.go
- slice/slice_test.go
> feat:(slice add AppendIfAbsent function)

- datetime/datetime.go
> expand BeginOfWeek、EndOfWeek

- docs/structs/field.md
- docs/structs/field_zh-CN.md
- docs/structs/struct.md
> add the struct package english docs

- system/os.go
- system/os_linux.go
- system/os_windows.go
```go
//windows 执行时隐藏执行窗口
system.ExecCommand(command string, system.WithWinHide()) 
//...
```
> [FEATURE] system 中添加Option

- stream/stream.go
- stream/stream_example_test.go
- stream/stream_test.go
> feat:add FindLast for stream

- validator/validator.go
- validator/validator_example_test.go
- validator/validator_test.go
feat: add ContainNumber for validator
> feat: add ContainNumber for validator

- datetime/datetime.go
- datetime/datetime_test.go
> 增加判断某个日期是一年当中的第几天的方法

- datetime/datetime.go
- datetime/datetime_test.go
> 新增判断是否是周末的方法

- netutil/http.go
- netutil/http_test.go
添加了`SendRequest`方法对于上传文件的支持，现在可以通过在`HttpRequest`定义File字段内容来上传文件，当检测到包含文件时，会自动将`header`的`content-type`修改为`multipart/form-data`.
上传文件的用法参考以下：
```golang
client := NewHttpClient()
request := &HttpRequest{
RawURL:   server.URL,
Method:   "POST",
File:     &File{Path: tmpFile.Name(), FieldName: "image", FileName: "testImage.jpg"},
// File:     &File{Content: []byte("file content"), FieldName: "image", FileName: "testImage.jpg"},
FormData: url.Values{"key1": {"value1"}, "key2": {"value2"}}, // FormData可为nil
}
resp, err := client.SendRequest(request)
```
> feat: Add support for uploading files in SendRequest

- docs/pointer.md
I'm really sorry, I tried to re-check my previous pr, but I found the message that needed to be deleted.
> fix: remove unused message in pointer.md

- datastructure/hashmap/hashmap.go
The get and contains functions, which get the first element of the linked list directly, now get the value by traversing the list
> fix: use loop to get value . On Get() and Contains()

- datastructure/hashmap/hashmap.go
- datastructure/hashmap/hashmap_test.go
- datastructure/list/copyonwritelist.go
- datastructure/list/copyonwritelist_test.go
- datastructure/list/list.go
- docs/datastructure/copyonwritelist.md
- docs/datastructure/copyonwritelist_zh-CN.md
feat: add CopyOnWriteList. A thread-safe list.
Includes some basic functions
> feat: add CopyOnWriteList. A thread-safe list.

- docs/api/packages/fileutil.md
- docs/en/api/packages/fileutil.md
- fileutil/file.go
- fileutil/file_example_test.go
- fileutil/file_test.go
Support ReadFile From `remote URL` or `local file`, carrying the reader return value will have better scalability.
> feat(fileutil): add ReadFile func

- fileutil/file.go
launch/fileutil/CurrentPath: support linux and windows dir
> [opt] currentPath support windows and linux

- README_zh-CN.md
- validator/validator.go
- validator/validator_example_test.go
- validator/validator_test.go
生日不能大于今日和小于1900年，因为市级太多因此没有效验，如不需要可关
> fix(validator): [IsChineseIdNum] fix 身份证效验 新增 省份、生日、效验码效验，修改ContainLower/IsNumber 注释错误

- algorithm/sort.go
If it is a sorted slice, reduce unnecessary loops。
> improvement:optimize bubble sort

- README.md
- README_zh-CN.md
- docs/api/packages/struct.md
- docs/en/api/packages/struct.md
- structs/field.go
- structs/field_test.go
1. add func: IsTargetType
2. docs error repair
> add new func & docs error repair

- random/random.go
正好最近看到一篇关于随机字符串生成的文章，原文链接：[Golang生成随机字符串的八种方式与性能测试-云社区-华为云 (huaweicloud.com)](https://bbs.huaweicloud.com/blogs/419489?utm_source=juejin&utm_medium=bbs-ex&utm_campaign=other&utm_content=content#H21)，[How to generate a random string of a fixed length in Go? - Stack Overflow](https://stackoverflow.com/questions/22892120/how-to-generate-a-random-string-of-a-fixed-length-in-go)
所以打算根据文章中提到的方法优化`random`的随机字符串生成方法
> 重构随机字符串生成refactor:refactor random function

- function/predicate.go
- function/predicate_test.go
Enable the execution of assertion functions in a functional manner.
> Add functional predicate

- README.md
- docs/api/packages/datastructure/optional.md
- docs/en/api/packages/datastructure/optional.md
> Fix optional doc links

- function/predicate.go
- function/predicate_example_test.go
- function/predicate_test.go
Add new function, Xnor, designed to create a composed predicate representing the logical Exclusive NOR (XNOR) operation applied to a list of predicates. The XNOR operation is a logical operation that returns true only if all operands have the same boolean value
> Add functional predicate XNOR

- cryptor/crypto.go
> feat: more readable panic

- slice/slice.go
- slice/slice_example_test.go
- slice/slice_test.go
SetToDefaultIf sets elements to their zero value if they match the given predicate. It retains the positions of the elements in the slice. It returns slice of T and the count of modified slice items
> Slice: Add SetToDefaultIf

- datastructure/set/set.go
- datastructure/set/set_test.go
- docs/api/packages/datastructure/set.md
- docs/en/api/packages/datastructure/set.md
> feat(set, doc): add ToSlice,ToSortedSlice method，fix doc

- fileutil/file.go
[填坑](https://github.com/duke-git/lancet/issues/188)
> 增加ParallelChunkRead方法，分块并发读取超大文本

- docs/api/packages/strutil.md
- docs/en/api/packages/strutil.md
- strutil/string.go
- strutil/string_example_test.go
- strutil/string_test.go
Add the Concat method with ease of use and efficiency in mind.
> add Concat method

- algorithm/lrucache.go
fix the bugs mentioned in issue $251:
> fix(algorithm): fix bug of lrucache in issue #251

- docs/api/packages/fileutil.md
- docs/api/packages/random.md
- fileutil/file.go
- fileutil/file_test.go
- fileutil/file_windows.go
- fileutil/file_windows_test.go
- go.mod
- go.sum
- random/random.go
- random/random_test.go
GetExeDllVersion 函数,用于获取exe和dll的版本号.
RandNumLen 函数,用于获取指定长度的随机数.
> feat:add GetExeDllVersion for fileutil,random,package

- concurrency/channel.go
- concurrency/channel_example_test.go
- concurrency/channel_test.go
make Bridge not block in the first stream that not closed
> make Bridge not block in the first stream that not closed

- convertor/convertor.go
- convertor/convertor_test.go
Support pass pointer to convert.ToString
> compatible with pointer in convert.ToString

- slice/slice.go
Simple refactor of ForEach functions to become more Go idiomatic.
> refactor(package): [slice] Simple refactor of ForEach
